services:
  - type: web
    name: designli-api
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install -g pnpm@9.15.4 && pnpm install && pnpm --filter @designli-challenge/shared build && pnpm --filter @designli-challenge/api prisma:generate && pnpm --filter @designli-challenge/api prisma:migrate:deploy && pnpm --filter @designli-challenge/api build
    startCommand: cd apps/api && pnpm start:prod
    envVars:
      - key: NODE_VERSION
        value: '20.18.0'
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: 'file:./dev.db'
    healthCheckPath: /
